var _token='';
try{_token=API.getToken()||'';}catch(e){_token=localStorage.getItem('nm_token')||'';}
var me=JSON.parse(localStorage.getItem('nm_me')||'null');
var currentChatId=null;
var currentChatData=null;
var messages=[];
var pollingTimer=null;
var lastMessageId=0;
var replyTo=null;
var editingMsgId=null;
var pendingRegEmail='';
var pendingResetEmail='';
var twoFAPending='';
var pendingJoinSlug=null;
var EMOJIS=['😀','😂','🥰','😎','🤔','😅','🤣','😊','🙏','👍','❤️','🔥','💯','🎉','👋','🤝','💪','🙌','👏','✅','⭐','🚀','💡','🎯','🤯','😤','💀','👀','🫡','🧠'];

function escHtml(str){return String(str||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function formatTime(dateStr){if(!dateStr)return'';var d=new Date(dateStr);var now=new Date();var isToday=d.toDateString()===now.toDateString();var yesterday=new Date(now);yesterday.setDate(now.getDate()-1);var isYesterday=d.toDateString()===yesterday.toDateString();if(isToday)return d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});if(isYesterday)return'Вчера';return d.toLocaleDateString('ru-RU',{day:'numeric',month:'short'});}
function formatDateFull(dateStr){if(!dateStr)return'';return new Date(dateStr).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}
function formatBytes(bytes){if(!bytes)return'';var k=1024;var sizes=['Б','КБ','МБ','ГБ'];var i=Math.floor(Math.log(bytes)/Math.log(k));return(bytes/Math.pow(k,i)).toFixed(1)+' '+sizes[i];}
function toast(msg,type){var cont=document.getElementById('toast-container');var el=document.createElement('div');el.className='toast';var icon=type==='success'?'✅':type==='error'?'❌':'ℹ️';el.innerHTML='<span>'+icon+'</span> <span>'+escHtml(msg)+'</span>';cont.appendChild(el);setTimeout(function(){el.remove();},3500);}
function errMsg(e){if(typeof e==='string')return e;return e?.error||e?.detail||e?.message||JSON.stringify(e)||'Ошибка';}
function showErr(id,msg){var el=document.getElementById(id);if(el){el.style.display='block';el.textContent=msg;}}
function hideErr(id){var el=document.getElementById(id);if(el)el.style.display='none';}
function showStep(id){document.querySelectorAll('.auth-step').forEach(function(s){s.classList.remove('active');});var el=document.getElementById(id);if(el)el.classList.add('active');}
function closeModal(id){var el=document.getElementById(id);if(el)el.classList.remove('active');}
function openModal(id){var el=document.getElementById(id);if(el)el.classList.add('active');}
function avatarContent(name,url,size){if(url)return'<img src="'+url+'" style="width:100%;height:100%;object-fit:cover;border-radius:50%"/>';var initials=(name||'?').split(' ').map(function(w){return w[0];}).join('').toUpperCase().slice(0,2);var colors=['#5eead4','#38bdf8','#818cf8','#c084fc','#f472b6','#fb7185'];var color=colors[(name||'').charCodeAt(0)%colors.length];return'<div style="width:100%;height:100%;border-radius:50%;background:linear-gradient(135deg,'+color+'33,'+color+'11);color:'+color+';display:flex;align-items:center;justify-content:center;font-weight:700;font-size:'+(size*0.4)+'px;text-shadow:0 0 10px '+color+'44">'+initials+'</div>';}
function setAvatar(elId,name,url,size){var el=document.getElementById(elId);if(!el)return;el.style.width=size+'px';el.style.height=size+'px';el.innerHTML=avatarContent(name,url,size);}

function switchAuthTab(tab){var tabs=['login','register','reset'];document.querySelectorAll('.auth-tab').forEach(function(t,i){t.classList.toggle('active',tabs[i]===tab);});hideErr('login-err');hideErr('reg-err');hideErr('reset-err');if(tab==='login')showStep('step-login');else if(tab==='register')showStep('step-register');else if(tab==='reset')showStep('step-reset');}
function buildCodeInputs(containerId,len){var c=document.getElementById(containerId);c.innerHTML='';for(var i=0;i<len;i++){var inp=document.createElement('input');inp.className='code-box';inp.maxLength=1;inp.inputMode='numeric';inp.addEventListener('input',function(idx){return function(e){if(e.target.value&&idx<len-1)c.children[idx+1].focus();};}(i));inp.addEventListener('keydown',function(idx){return function(e){if(e.key==='Backspace'&&!inp.value&&idx>0)c.children[idx-1].focus();};}(i));c.appendChild(inp);}c.children[0].focus();}
function getCodeValue(containerId){return Array.from(document.getElementById(containerId).children).map(function(i){return i.value;}).join('');}

async function doLogin(){hideErr('login-err');var identifier=document.getElementById('login-id').value.trim();var password=document.getElementById('login-pw').value;if(!identifier||!password){showErr('login-err','Заполните все поля');return;}try{var res=await API.login({identifier:identifier,password:password});if(res.two_fa_required){twoFAPending=identifier;buildCodeInputs('code-inputs-2fa',6);showStep('step-2fa');}else{loginSuccess(res);}}catch(e){var msg=errMsg(e);if(msg.includes('not verified')){showStep('step-verify');pendingRegEmail=identifier;buildCodeInputs('code-inputs-verify',6);}else showErr('login-err',msg);}}
async function do2FA(){var code=getCodeValue('code-inputs-2fa');if(code.length<6){showErr('twofa-err','Введите 6-значный код');return;}try{var res=await API.verify2fa({identifier:twoFAPending,code:code});loginSuccess(res);}catch(e){showErr('twofa-err',errMsg(e));}}
async function doRegister(){hideErr('reg-err');var email=document.getElementById('reg-email').value.trim();var username=document.getElementById('reg-username').value.trim();var display_name=document.getElementById('reg-name').value.trim();var password=document.getElementById('reg-pw').value;if(!email||!username||!display_name||!password){showErr('reg-err','Заполните все поля');return;}try{await API.register({email:email,username:username,display_name:display_name,password:password});pendingRegEmail=email;buildCodeInputs('code-inputs-verify',6);showStep('step-verify');toast('Код отправлен на почту','success');}catch(e){showErr('reg-err',errMsg(e));}}
async function doVerify(){var code=getCodeValue('code-inputs-verify');if(code.length<6){showErr('verify-err','Введите 6-значный код');return;}try{await API.verifyEmail({email:pendingRegEmail,code:code});toast('Email подтверждён! Войдите.','success');showStep('step-login');}catch(e){showErr('verify-err',errMsg(e));}}
async function doResetRequest(){hideErr('reset-err');var email=document.getElementById('reset-email').value.trim();if(!email){showErr('reset-err','Введите email');return;}try{await API.resetPasswordReq({email:email});pendingResetEmail=email;buildCodeInputs('code-inputs-reset',6);showStep('step-reset-confirm');toast('Код отправлен','success');}catch(e){showErr('reset-err',errMsg(e));}}
async function doResetConfirm(){hideErr('reset-confirm-err');var code=getCodeValue('code-inputs-reset');var new_password=document.getElementById('reset-newpw').value;if(code.length<6||!new_password){showErr('reset-confirm-err','Заполните все поля');return;}try{await API.resetPasswordConfirm({email:pendingResetEmail,code:code,new_password:new_password});toast('Пароль изменён! Войдите снова.','success');showStep('step-login');}catch(e){showErr('reset-confirm-err',errMsg(e));}}

function loginSuccess(res){_token=res.access_token;API.setToken(_token);me={id:res.user_id,username:res.username,display_name:res.display_name};localStorage.setItem('nm_me',JSON.stringify(me));document.getElementById('auth-screen').classList.add('hidden');var app=document.getElementById('main-app');app.classList.add('visible');initApp();}
function logout(){if(_token)API.logout().catch(function(){});_token='';me=null;currentChatId=null;clearInterval(pollingTimer);API.setToken('');localStorage.removeItem('nm_me');document.getElementById('main-app').classList.remove('visible');var auth=document.getElementById('auth-screen');auth.classList.remove('hidden');closeModal('settings-modal');}

async function initApp(){await loadMyProfile();loadChatList();buildEmojiGrid();startPolling();checkUrlRoute();}
async function loadMyProfile(){try{var p=await API.me();me={...me,...p};localStorage.setItem('nm_me',JSON.stringify(me));setAvatar('my-avatar',p.display_name,p.avatar_url,36);}catch(e){}}

function checkUrlRoute(){var path=location.pathname;if(path.startsWith('/join/')){var slug=path.split('/').pop();if(_token&&me){openNewChatModal();switchNewChatTab('join');document.getElementById('join-slug').value=slug;previewJoin();}else{pendingJoinSlug=slug;}}}

async function loadChatList(){try{var chats=await API.listChats();renderChatList(chats);}catch(e){console.error(e);}}

function renderChatList(chats){var el=document.getElementById('chat-list');if(!chats.length){el.innerHTML='<div style="padding:24px;text-align:center;color:var(--text-secondary);font-size:14px">Нет чатов — начните новый!</div>';return;}el.innerHTML=chats.map(function(c){return chatItemHtml(c);}).join('');}

function chatItemHtml(c){var typeIcon=c.chat_type==='group'?'👥':c.chat_type==='channel'?'📢':'';var lastMsg=c.last_message;var preview='';if(lastMsg){if(lastMsg.is_deleted)preview='<i style="color:var(--text-secondary)">Сообщение удалено</i>';else if(lastMsg.msg_type==='media')preview='📎 Медиафайл';else if(lastMsg.msg_type==='voice')preview='🎤 Голосовое';else if(lastMsg.msg_type==='circle')preview='⭕ Видеокружок';else preview=escHtml(lastMsg.content||'');}var time=lastMsg?formatTime(lastMsg.sent_at):'';var badges=(c.partner_badges||[]).map(function(b){return '<span class="badge-pill" style="background:'+b.color+'22;color:'+b.color+';border:1px solid '+b.color+'44">'+escHtml(b.icon)+'</span>';}).join('');var activeClass=c.id===currentChatId?'active':'';return '<div class="chat-item '+activeClass+'" id="chatitem-'+c.id+'" onclick="openChat('+c.id+')">'+'<div class="chat-avatar" style="width:48px;height:48px;font-size:18px">'+avatarContent(c.name,c.avatar_url)+'</div>'+'<div class="chat-info">'+'<div class="chat-name-row">'+'<div class="chat-name" style="display:flex;align-items:center;gap:5px">'+(typeIcon?'<span>'+typeIcon+'</span>':'')+escHtml(c.name)+badges+'</div>'+'<div class="chat-time">'+time+'</div>'+'</div>'+'<div class="chat-preview-row">'+'<div class="chat-preview">'+preview+'</div>'+(c.unread_count>0?'<div class="chat-unread">'+(c.unread_count>99?'99+':c.unread_count)+'</div>':'')+'</div>'+'</div>'+'</div>';}

async function openChat(chatId){currentChatId=chatId;lastMessageId=0;messages=[];replyTo=null;editingMsgId=null;cancelReply();document.querySelectorAll('.chat-item').forEach(function(el){el.classList.remove('active');});var item=document.getElementById('chatitem-'+chatId);if(item){item.classList.add('active');}document.getElementById('welcome-screen').style.display='none';var chatView=document.getElementById('chat-view');chatView.style.display='flex';API.markRead(chatId).catch(function(){});var sidebar=document.getElementById('sidebar');if(window.innerWidth<=900)sidebar.classList.add('mobile-hidden');try{var chat=await API.getChat(chatId);currentChatData=chat;renderChatHeader(chat);await loadMessages(chatId);document.getElementById('members-panel').classList.remove('open');document.getElementById('profile-panel').classList.remove('open');}catch(e){toast('Ошибка загрузки чата','error');}}

function goBackToSidebar(){document.getElementById('sidebar').classList.remove('mobile-hidden');var chatView=document.getElementById('chat-view');chatView.style.display='none';document.getElementById('welcome-screen').style.display='flex';}

function renderChatHeader(chat){var name=chat.name||chat.partner?.display_name||'?';var typeIcon=chat.chat_type==='group'?'👥':chat.chat_type==='channel'?'📢':'';document.getElementById('chat-header-name').innerHTML=(typeIcon?typeIcon+' ':'')+escHtml(name);var sub=chat.chat_type==='direct'?'@'+(chat.partner?.username||''):chat.members_count+' участников';document.getElementById('chat-header-sub').textContent=sub;setAvatar('chat-header-avatar',name,chat.avatar_url||chat.partner?.avatar_url,40);document.getElementById('members-btn').style.display=chat.chat_type!=='direct'?'flex':'none';}

async function loadMessages(chatId){try{var res=await API.history(chatId,1);messages=res.messages||[];if(messages.length)lastMessageId=messages[messages.length-1].id;renderMessages();scrollToBottom();}catch(e){}}

function renderMessages(){var area=document.getElementById('messages-area');area.innerHTML='';var lastDate='';messages.forEach(function(msg,idx){var d=new Date(msg.sent_at).toLocaleDateString('ru-RU',{day:'numeric',month:'long'});if(d!==lastDate){lastDate=d;area.innerHTML+='<div class="day-separator">'+d+'</div>';}area.innerHTML+=renderMsg(msg);});area.querySelectorAll('.msg-wrap').forEach(function(el,i){el.addEventListener('contextmenu',function(e){e.preventDefault();showMsgCtxMenu(e,parseInt(el.dataset.msgid));});});}

function renderMsg(msg){var isOwn=msg.sender_id===me?.id;var deleted=msg.is_deleted;var replyBlock=msg.reply_to_id?renderReplyBlock(msg.reply_to_id):'';var mediaBlock=renderMedia(msg);var reactions=renderReactions(msg);var badges=(msg.sender_badges||[]).map(function(b){return '<span class="badge-pill" style="background:'+b.color+'22;color:'+b.color+';border:1px solid '+b.color+'44" title="'+escHtml(b.name)+'">'+escHtml(b.icon)+'</span>';}).join('');var edited=msg.edited_at?'<span class="msg-edited">ред.</span>':'';var content='';if(deleted)content='<span class="msg-deleted">🗑 Сообщение удалено</span>';else content='<span class="msg-text">'+escHtml(msg.content||'')+'</span>';var keyboard=renderInlineKeyboard(msg);return '<div class="msg-wrap '+(isOwn?'own':'')+'" data-msgid="'+msg.id+'">'+(isOwn?'':'<div class="chat-avatar" style="width:32px;height:32px;font-size:13px;flex-shrink:0">'+avatarContent(msg.sender_display_name,msg.sender_avatar_url)+'</div>')+'<div class="msg-bubble" style="position:relative">'+(isOwn||deleted?'':'<div class="msg-sender">'+escHtml(msg.sender_display_name||msg.sender_username||'')+' '+badges+'</div>')+replyBlock+content+mediaBlock+'<div class="msg-footer">'+edited+'<span class="msg-time">'+formatTime(msg.sent_at)+'</span></div>'+reactions+'</div>'+keyboard+'</div>';}

function renderInlineKeyboard(msg){if(!msg.reply_markup||!msg.reply_markup.inline_keyboard)return'';var rows=msg.reply_markup.inline_keyboard;var html='<div class="inline-keyboard">';rows.forEach(function(row){html+='<div class="inline-keyboard-row">';row.forEach(function(btn){html+='<button class="inline-keyboard-btn" onclick="handleCallbackButton('+msg.id+','+msg.chat_id+',\''+escHtml(btn.callback_data||'')+'\')">'+escHtml(btn.text||'')+'</button>';});html+='</div>';});html+='</div>';return html;}

async function handleCallbackButton(messageId,chatId,data){if(!data)return;try{await API.callbackQuery({message_id:messageId,chat_id:chatId,data:data});toast('Отправлено','success');}catch(e){toast(errMsg(e),'error');}}

function renderReplyBlock(replyId){var orig=messages.find(function(m){return m.id===replyId;});if(!orig)return'<div class="msg-reply"><div class="msg-reply-name">Ответ</div><div class="msg-reply-text">Сообщение недоступно</div></div>';return'<div class="msg-reply" onclick="scrollToMsg('+replyId+')"><div class="msg-reply-name">'+escHtml(orig.sender_display_name||orig.sender_username||'')+'</div><div class="msg-reply-text">'+escHtml(orig.content||'[медиа]')+'</div></div>';}

function renderMedia(msg){if(!msg.media_url)return'';var url=msg.media_url;if(msg.media_type?.startsWith('image'))return'<div class="msg-media"><img src="'+url+'" loading="lazy" onclick="window.open(\''+url+'\')"/></div>';if(msg.media_type?.startsWith('video'))return'<div class="msg-media"><video src="'+url+'" controls></video></div>';if(msg.msg_type==='voice')return'<div class="voice-msg"><button class="voice-play" onclick="new Audio(\''+url+'\').play()">▶</button><span>🎤 Голосовое</span></div>';var size=msg.media_size?formatBytes(msg.media_size):'';return'<div class="msg-file" onclick="window.open(\''+url+'\')"><span style="font-size:20px">📎</span><div style="flex:1;min-width:0"><div style="font-size:13px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+escHtml(msg.media_name||'Файл')+'</div><div style="font-size:11px;color:var(--text-secondary)">'+size+'</div></div></div>';}

function renderReactions(msg){if(!msg.reactions||!Object.keys(msg.reactions).length)return'';var chips=Object.entries(msg.reactions).map(function(pair){var emoji=pair[0],count=pair[1];return'<div class="reaction-chip" onclick="reactMsg('+msg.id+',\''+emoji+'\')"><span>'+emoji+'</span><span>'+count+'</span></div>';}).join('');return'<div class="msg-reactions">'+chips+'</div>';}

function scrollToMsg(msgId){var el=document.querySelector('[data-msgid="'+msgId+'"]');if(el){el.scrollIntoView({behavior:'smooth',block:'center'});var bubble=el.querySelector('.msg-bubble');if(bubble){bubble.style.boxShadow='0 0 20px var(--accent)';setTimeout(function(){bubble.style.boxShadow='';},1500);}}}
function scrollToBottom(){var area=document.getElementById('messages-area');area.scrollTop=area.scrollHeight;}

async function reactMsg(msgId,emoji){if(!currentChatId)return;try{await API.react(currentChatId,msgId,emoji);await refreshMessages();}catch(e){toast(errMsg(e),'error');}}

var ctxMenuEl=null;
function showMsgCtxMenu(e,msgId){closeCtxMenu();var msg=messages.find(function(m){return m.id===msgId;});if(!msg||msg.is_deleted)return;var isOwn=msg.sender_id===me?.id;var items=[{label:'↩ Ответить',fn:'setReply('+msgId+')'},{label:'😊 Реакция',fn:'openReactPicker('+msgId+')'}];if(isOwn){items.push({label:'✏️ Редактировать',fn:'startEdit('+msgId+')'});items.push({label:'🗑 Удалить',fn:'deleteMsg('+msgId+')',danger:true});}else if(currentChatData?.chat_type!=='direct'){items.push({label:'🗑 Удалить',fn:'deleteMsg('+msgId+')',danger:true});}var menu=document.createElement('div');menu.className='msg-ctx-menu';menu.style.cssText='position:fixed;left:'+Math.min(e.clientX,window.innerWidth-200)+'px;top:'+Math.min(e.clientY,window.innerHeight-160)+'px;';menu.innerHTML=items.map(function(it){return'<div class="msg-ctx-item '+(it.danger?'danger':'')+'" onclick="'+it.fn+';closeCtxMenu()">'+it.label+'</div>';}).join('');document.body.appendChild(menu);ctxMenuEl=menu;setTimeout(function(){document.addEventListener('click',closeCtxMenu,{once:true});},0);}
function closeCtxMenu(){if(ctxMenuEl){ctxMenuEl.remove();ctxMenuEl=null;}}

function setReply(msgId){var msg=messages.find(function(m){return m.id===msgId;});if(!msg)return;replyTo=msgId;editingMsgId=null;document.getElementById('reply-bar').classList.add('active');document.getElementById('reply-bar-name').textContent=msg.sender_display_name||msg.sender_username;document.getElementById('reply-bar-text').textContent=msg.content||'[медиа]';document.getElementById('msg-input').focus();}
function cancelReply(){replyTo=null;editingMsgId=null;document.getElementById('reply-bar').classList.remove('active');document.getElementById('msg-input').value='';}
function startEdit(msgId){var msg=messages.find(function(m){return m.id===msgId;});if(!msg)return;editingMsgId=msgId;replyTo=null;document.getElementById('reply-bar').classList.add('active');document.getElementById('reply-bar-name').textContent='Редактирование';document.getElementById('reply-bar-text').textContent=msg.content;document.getElementById('msg-input').value=msg.content;document.getElementById('msg-input').focus();}
async function deleteMsg(msgId){if(!currentChatId)return;try{await API.deleteMessage(currentChatId,msgId);await refreshMessages();}catch(e){toast(errMsg(e),'error');}}

function openReactPicker(msgId){var popup=document.createElement('div');popup.style.cssText='position:fixed;z-index:999;background:var(--sidebar-bg);border:1px solid var(--border);border-radius:12px;padding:10px;box-shadow:0 8px 24px rgba(0,0,0,0.5);display:grid;grid-template-columns:repeat(6,1fr);gap:4px;';var target=document.querySelector('[data-msgid="'+msgId+'"]');if(target){var r=target.getBoundingClientRect();popup.style.top=(r.top-70)+'px';popup.style.left=Math.min(r.left,window.innerWidth-220)+'px';}popup.innerHTML=EMOJIS.map(function(e){return'<div class="emoji-cell" onclick="reactMsg('+msgId+',\''+e+'\');this.parentElement.remove()">'+e+'</div>';}).join('');document.body.appendChild(popup);setTimeout(function(){document.addEventListener('click',function(){popup.remove();},{once:true});},0);}

async function sendMessage(){if(!currentChatId)return;var input=document.getElementById('msg-input');var content=input.value.trim();if(editingMsgId){if(!content)return;try{await API.editMessage(currentChatId,editingMsgId,{content:content});cancelReply();input.value='';autoResize(input);await refreshMessages();toast('Сообщение отредактировано','success');}catch(e){toast(errMsg(e),'error');}return;}if(!content)return;input.value='';autoResize(input);try{var msg=await API.sendMessage(currentChatId,{content:content,reply_to_id:replyTo||null});messages.push(msg);if(msg.id>lastMessageId)lastMessageId=msg.id;renderMessages();scrollToBottom();API.markRead(currentChatId).catch(function(){});loadChatList();}catch(e){toast(errMsg(e),'error');}}

function onMsgKey(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}}
function autoResize(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,120)+'px';}
function triggerFileUpload(){document.getElementById('file-input').click();}

async function handleFileSelect(input){var file=input.files[0];if(!file||!currentChatId)return;input.value='';var subtype=file.type.startsWith('audio')?'voice':'media';await uploadAndSend(file,subtype);}

async function uploadAndSend(file,subtype){var CHUNK=262144;var total=Math.ceil(file.size/CHUNK);var prog=document.getElementById('upload-progress');var fill=document.getElementById('progress-fill');var pct=document.getElementById('progress-pct');prog.classList.add('active');fill.style.width='0%';pct.textContent='0%';try{var init=await API.initUpload({filename:file.name,total_chunks:total,file_size:file.size,media_subtype:subtype});for(var i=0;i<total;i++){var slice=file.slice(i*CHUNK,(i+1)*CHUNK);var b64=await readSliceAsBase64(slice);await API.uploadChunk({upload_id:init.upload_id,chunk_index:i,chunk_base64:b64});var p=Math.round((i+1)/total*100);fill.style.width=p+'%';pct.textContent=p+'%';}var msg=await API.sendMessage(currentChatId,{content:'',upload_id:init.upload_id,reply_to_id:replyTo||null});messages.push(msg);if(msg.id>lastMessageId)lastMessageId=msg.id;renderMessages();scrollToBottom();loadChatList();}catch(e){toast('Ошибка загрузки: '+errMsg(e),'error');}finally{prog.classList.remove('active');}}

function readSliceAsBase64(slice){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onload=function(){resolve(reader.result.split(',')[1]);};reader.onerror=reject;reader.readAsDataURL(slice);});}

function buildEmojiGrid(){var grid=document.getElementById('emoji-picker');grid.innerHTML=EMOJIS.map(function(e){return'<div class="emoji-cell" onclick="insertEmoji(\''+e+'\')">'+e+'</div>';}).join('');}
function toggleEmojiPicker(){document.getElementById('emoji-picker').classList.toggle('active');}
function insertEmoji(emoji){var inp=document.getElementById('msg-input');inp.value+=emoji;inp.focus();document.getElementById('emoji-picker').classList.remove('active');}
document.addEventListener('click',function(e){if(!e.target.closest('.emoji-btn'))document.getElementById('emoji-picker').classList.remove('active');});

function startPolling(){clearInterval(pollingTimer);pollingTimer=setInterval(pollMessages,3000);}

async function pollMessages(){if(!currentChatId)return;try{var res=await API.history(currentChatId,1);var newMsgs=(res.messages||[]).filter(function(m){return m.id>lastMessageId;});if(newMsgs.length){messages.push.apply(messages,newMsgs);lastMessageId=messages[messages.length-1].id;renderMessages();var area=document.getElementById('messages-area');if(area.scrollHeight-area.scrollTop-area.clientHeight<120)scrollToBottom();API.markRead(currentChatId).catch(function(){});}loadChatList();}catch(e){}}

async function refreshMessages(){try{var res=await API.history(currentChatId,1);messages=res.messages||[];lastMessageId=messages.length?messages[messages.length-1].id:0;renderMessages();}catch(e){}}

async function toggleMembers(){var panel=document.getElementById('members-panel');panel.classList.toggle('open');if(panel.classList.contains('open'))loadMembers();}
async function toggleProfile(){var panel=document.getElementById('profile-panel');panel.classList.toggle('open');if(panel.classList.contains('open')&&currentChatData){if(currentChatData.chat_type==='direct'&&currentChatData.partner)loadUserProfile(currentChatData.partner.username);else renderChatProfile(currentChatData);}}

async function loadMembers(){if(!currentChatId)return;var list=document.getElementById('members-list');list.innerHTML='<div style="padding:12px;text-align:center;color:var(--text-secondary);font-size:13px">Загрузка...</div>';try{var members=await API.getMembers(currentChatId);list.innerHTML=members.map(function(m){var roleIcon=m.role==='owner'?'👑':m.role==='admin'?'⚡':'';var badges=(m.badges||[]).map(function(b){return'<span class="badge-pill" style="background:'+b.color+'22;color:'+b.color+';border:1px solid '+b.color+'44">'+escHtml(b.icon)+'</span>';}).join('');return'<div class="member-item" onclick="openUserProfile(\''+escHtml(m.username)+'\')">'+'<div class="chat-avatar" style="width:34px;height:34px;font-size:13px">'+avatarContent(m.display_name,m.avatar_url)+'</div>'+'<div style="flex:1;min-width:0">'+'<div style="font-size:13px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+escHtml(m.display_name||m.username)+' '+badges+'</div>'+'<div style="font-size:11px;color:var(--text-secondary)">'+roleIcon+' '+m.role+' · @'+escHtml(m.username)+'</div>'+'</div>'+'</div>';}).join('');}catch(e){list.innerHTML='<div style="padding:12px;color:var(--text-secondary);text-align:center">Ошибка</div>';}}

async function openUserProfile(username){document.getElementById('profile-panel').classList.add('open');await loadUserProfile(username);}
async function loadUserProfile(username){try{var p=await API.getProfile(username);renderUserProfile(p);}catch(e){}}

function renderUserProfile(p){setAvatar('panel-avatar',p.display_name,p.avatar_url,80);document.getElementById('panel-name').textContent=p.display_name||p.username;document.getElementById('panel-username').textContent='@'+p.username;document.getElementById('panel-bio').textContent=p.bio||'';document.getElementById('panel-badges').innerHTML=(p.badges||[]).map(function(b){return'<span class="badge-pill" style="background:'+b.color+'22;color:'+b.color+';border:1px solid '+b.color+'44">'+escHtml(b.icon)+' '+escHtml(b.name)+'</span>';}).join('');document.getElementById('panel-actions').innerHTML=p.id!==me?.id?'<button class="auth-btn" style="width:auto" onclick="startDM(\''+escHtml(p.username)+'\')">Написать</button>':'<button class="auth-btn" style="width:auto;background:var(--input-bg)" onclick="openSettings()">Редактировать профиль</button>';}

function renderChatProfile(chat){setAvatar('panel-avatar',chat.name,chat.avatar_url,80);document.getElementById('panel-name').textContent=chat.name;document.getElementById('panel-username').textContent=chat.username?'@'+chat.username:'';document.getElementById('panel-bio').textContent=chat.description||'';document.getElementById('panel-badges').innerHTML='';document.getElementById('panel-actions').innerHTML='<button class="auth-btn" style="width:auto;background:var(--danger)" onclick="leaveChat()">Покинуть</button>';}

async function startDM(username){closeAllPanels();try{var res=await API.openDM(username);await loadChatList();openChat(res.chat_id);}catch(e){toast(errMsg(e),'error');}}
async function leaveChat(){if(!currentChatId)return;if(!confirm('Покинуть чат?'))return;try{await API.leaveChat(currentChatId);currentChatId=null;currentChatData=null;document.getElementById('chat-view').style.display='none';document.getElementById('welcome-screen').style.display='flex';loadChatList();toast('Вы покинули чат','success');}catch(e){toast(errMsg(e),'error');}}

function openMyProfile(){openSettings();}
function closeAllPanels(){document.getElementById('members-panel').classList.remove('open');document.getElementById('profile-panel').classList.remove('open');}

function openSettings(){openModal('settings-modal');loadSettingsProfile();}
function switchSettingsTab(tab){var tabs=['profile','security','sessions'];document.querySelectorAll('#settings-modal .tab-pill').forEach(function(t,i){t.classList.toggle('active',tabs[i]===tab);});tabs.forEach(function(t){var el=document.getElementById('settings-'+t);if(el)el.classList.toggle('active',t===tab);});if(tab==='sessions')loadSessions();if(tab==='security')loadSecuritySettings();}
function loadSettingsProfile(){if(!me)return;document.getElementById('edit-display-name').value=me.display_name||'';document.getElementById('edit-username').value=me.username||'';document.getElementById('edit-bio').value=me.bio||'';document.getElementById('settings-display-name').textContent=me.display_name||'';document.getElementById('settings-username-display').textContent='@'+(me.username||'');var wrap=document.getElementById('settings-avatar-wrap');wrap.innerHTML='<input type="file" id="avatar-input" style="display:none" accept="image/*" onchange="uploadAvatar(this)"/>'+avatarContent(me.display_name,me.avatar_url,56);}
function loadSecuritySettings(){var toggle=document.getElementById('twofa-toggle');toggle.classList.toggle('on',!!me?.two_fa_enabled);}
function toggle2FA(){var pw=document.getElementById('twofa-pw-wrap');pw.style.display=pw.style.display==='none'?'flex':'none';pw.style.flexDirection='column';}
async function confirm2FA(){var password=document.getElementById('twofa-pw').value;var enabled=!me?.two_fa_enabled;try{await API.toggle2fa({enabled:enabled,password:password});me.two_fa_enabled=enabled;localStorage.setItem('nm_me',JSON.stringify(me));document.getElementById('twofa-toggle').classList.toggle('on',enabled);document.getElementById('twofa-pw-wrap').style.display='none';toast('2FA '+(enabled?'включена':'отключена'),'success');}catch(e){toast(errMsg(e),'error');}}
async function saveProfile(){hideErr('settings-err');var body={};var dn=document.getElementById('edit-display-name').value.trim();var un=document.getElementById('edit-username').value.trim();var bio=document.getElementById('edit-bio').value.trim();if(dn)body.display_name=dn;if(un)body.username=un;body.bio=bio;try{var p=await API.updateProfile(body);me={...me,...p};localStorage.setItem('nm_me',JSON.stringify(me));setAvatar('my-avatar',me.display_name,me.avatar_url,36);loadSettingsProfile();toast('Профиль обновлён','success');}catch(e){showErr('settings-err',errMsg(e));}}
async function uploadAvatar(input){var file=input.files[0];if(!file)return;var reader=new FileReader();reader.onload=async function(){try{var b64=reader.result.split(',')[1];var res=await API.uploadAvatar(b64,file.name);me.avatar_url=res.avatar_url;localStorage.setItem('nm_me',JSON.stringify(me));setAvatar('my-avatar',me.display_name,me.avatar_url,36);loadSettingsProfile();toast('Аватар обновлён','success');}catch(e){toast(errMsg(e),'error');}};reader.readAsDataURL(file);}
async function loadSessions(){var list=document.getElementById('sessions-list');list.innerHTML='<div style="padding:12px;text-align:center;color:var(--text-secondary)">Загрузка...</div>';try{var sessions=await API.listSessions();list.innerHTML=sessions.map(function(s){return'<div class="member-item" style="margin:4px 0">'+'<span style="font-size:20px">💻</span><div style="flex:1">'+'<div style="font-size:13px;font-weight:600">'+escHtml(s.device_info||'Неизвестно')+'</div>'+'<div style="font-size:11px;color:var(--text-secondary)">'+escHtml(s.ip_address||'')+' · '+formatDateFull(s.last_active)+'</div>'+'</div>'+'<button class="icon-btn" onclick="kickSession('+s.id+')">🗑</button>'+'</div>';}).join('');}catch(e){list.innerHTML='<div style="padding:12px;color:var(--text-secondary);text-align:center">Ошибка</div>';}}
async function kickSession(id){try{await API.kickSession(id);loadSessions();toast('Сессия завершена','success');}catch(e){toast(errMsg(e),'error');}}

function openNewChatModal(){openModal('new-chat-modal');switchNewChatTab('direct');}
function switchNewChatTab(tab){var tabs=['direct','group','join'];document.querySelectorAll('#new-chat-modal .tab-pill').forEach(function(t,i){t.classList.toggle('active',tabs[i]===tab);});tabs.forEach(function(t){var el=document.getElementById('new-chat-'+t);if(el)el.classList.toggle('active',t===tab);});}

var userSearchTimer;
async function searchUsers(q){var res=document.getElementById('dm-search-results');if(!q.trim()){res.innerHTML='';return;}clearTimeout(userSearchTimer);userSearchTimer=setTimeout(async function(){try{var data=await API.search(q);var users=data.users||[];res.innerHTML=users.map(function(u){return'<div class="member-item" onclick="startDMFromModal(\''+escHtml(u.username)+'\')">'+'<div class="chat-avatar" style="width:36px;height:36px;font-size:14px">'+avatarContent(u.display_name,u.avatar_url)+'</div>'+'<div><div style="font-size:13px;font-weight:700">'+escHtml(u.display_name||u.username)+'</div><div style="font-size:11px;color:var(--text-secondary)">@'+escHtml(u.username)+'</div></div>'+'</div>';}).join('')||'<div style="color:var(--text-secondary);font-size:13px;padding:8px">Не найдено</div>';}catch(e){}},300);}
async function startDMFromModal(username){closeModal('new-chat-modal');await startDM(username);}

async function createGroupChat(){hideErr('create-chat-err');var name=document.getElementById('new-chat-name').value.trim();var description=document.getElementById('new-chat-desc').value.trim();var username=document.getElementById('new-chat-slug').value.trim();var chat_type=document.querySelector('input[name="chat-type"]:checked').value;if(!name){showErr('create-chat-err','Введите название');return;}try{var body={name:name,chat_type:chat_type};if(description)body.description=description;if(username)body.username=username;var res=await API.createGroup(body);closeModal('new-chat-modal');await loadChatList();openChat(res.chat_id);toast((chat_type==='group'?'Группа':'Канал')+' создана','success');}catch(e){showErr('create-chat-err',errMsg(e));}}

async function previewJoin(){var raw=document.getElementById('join-slug').value.trim();var slug=raw.split('/').pop();try{var info=await API.inviteInfo(slug);document.getElementById('join-preview').style.display='block';document.getElementById('join-preview').innerHTML='<div style="font-weight:700">'+escHtml(info.name)+'</div><div style="font-size:12px;color:var(--text-secondary)">'+info.chat_type+' · '+info.members_count+' участников</div><div style="font-size:12px;margin-top:4px">'+escHtml(info.description||'')+'</div>';}catch(e){toast('Не найдено','error');}}

async function joinChat(){var raw=document.getElementById('join-slug').value.trim();var slug=raw.split('/').pop();try{var res=await API.joinChat(slug);closeModal('new-chat-modal');await loadChatList();openChat(res.chat_id);toast('Вы вступили в чат!','success');}catch(e){toast(errMsg(e),'error');}}

var globalSearchTimer;
async function onSearchInput(q){var res=document.getElementById('search-results');if(!q.trim()){res.classList.remove('active');return;}clearTimeout(globalSearchTimer);globalSearchTimer=setTimeout(async function(){try{var data=await API.search(q);var html='';if(data.users?.length){html+='<div style="padding:8px 16px;font-size:12px;color:var(--text-secondary);font-weight:600">Пользователи</div>';html+=data.users.map(function(u){return'<div class="member-item" onclick="openUserProfile(\''+escHtml(u.username)+'\');closeSearch()">'+'<div class="chat-avatar" style="width:30px;height:30px;font-size:12px">'+avatarContent(u.display_name,u.avatar_url)+'</div>'+'<div><div style="font-size:13px;font-weight:700">'+escHtml(u.display_name||u.username)+'</div><div style="font-size:11px;color:var(--text-secondary)">@'+escHtml(u.username)+'</div></div></div>';}).join('');}if(data.chats?.length){html+='<div style="padding:8px 16px;font-size:12px;color:var(--text-secondary);font-weight:600">Чаты</div>';html+=data.chats.map(function(c){return'<div class="member-item" onclick="openChat('+c.id+');closeSearch()">'+'<span style="font-size:20px">'+(c.chat_type==='channel'?'📢':'👥')+'</span>'+'<div><div style="font-size:13px;font-weight:700">'+escHtml(c.name)+'</div><div style="font-size:11px;color:var(--text-secondary)">'+c.members_count+' участников</div></div></div>';}).join('');}if(data.messages?.length){html+='<div style="padding:8px 16px;font-size:12px;color:var(--text-secondary);font-weight:600">Сообщения</div>';html+=data.messages.map(function(m){return'<div class="member-item" onclick="openChat('+m.chat_id+');closeSearch()">'+'<div class="chat-avatar" style="width:30px;height:30px;font-size:12px">'+avatarContent(m.sender_display_name,'')+'</div>'+'<div><div style="font-size:13px;font-weight:700">'+escHtml(m.sender_display_name)+'</div><div style="font-size:12px;color:var(--text-secondary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:200px">'+escHtml(m.content||'')+'</div></div></div>';}).join('');}res.innerHTML=html||'<div style="padding:12px;color:var(--text-secondary);font-size:13px">Ничего не найдено</div>';res.classList.add('active');}catch(e){}},350);}
function closeSearch(){document.getElementById('search-results').classList.remove('active');document.getElementById('global-search').value='';}
function toggleSearch(){var bar=document.getElementById('search-bar-wrap');bar.style.display=bar.style.display==='none'?'block':'none';}

if(_token&&me){document.getElementById('auth-screen').classList.add('hidden');var app=document.getElementById('main-app');app.classList.add('visible');initApp();}else{buildCodeInputs('code-inputs-2fa',6);buildCodeInputs('code-inputs-verify',6);buildCodeInputs('code-inputs-reset',6);}

window.addEventListener('resize',function(){if(window.innerWidth>900)document.getElementById('sidebar').classList.remove('mobile-hidden');});
document.addEventListener('keydown',function(e){if(e.key==='Escape'){document.querySelectorAll('.modal-overlay.active').forEach(function(m){m.classList.remove('active');});closeSearch();closeCtxMenu();if(window.innerWidth<=900)document.getElementById('sidebar').classList.remove('mobile-hidden');}});
