// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUc0z-3CD_ni6XEjjekL7LzBfTNBCvS5I',
    appId: '1:31725064203:web:565db88ac605bf7f82370e',
    messagingSenderId: '31725064203',
    projectId: 'niosmess',
    authDomain: 'niosmess.firebaseapp.com',
    storageBucket: 'niosmess.firebasestorage.app',
    measurementId: 'G-GJ5Q6L2C1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIlq9dix4DYlLBNUF4eqsofZqh_uItUI',
    appId: '1:31725064203:android:6c5a6125b31dd11e82370e',
    messagingSenderId: '31725064203',
    projectId: 'niosmess',
    storageBucket: 'niosmess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuCq0fOoGQ8OMccJMRBXH1QyOt_9Lx7iE',
    appId: '1:31725064203:ios:02413506eb39d59282370e',
    messagingSenderId: '31725064203',
    projectId: 'niosmess',
    storageBucket: 'niosmess.firebasestorage.app',
    iosBundleId: 'com.example.niosmess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuCq0fOoGQ8OMccJMRBXH1QyOt_9Lx7iE',
    appId: '1:31725064203:ios:02413506eb39d59282370e',
    messagingSenderId: '31725064203',
    projectId: 'niosmess',
    storageBucket: 'niosmess.firebasestorage.app',
    iosBundleId: 'com.example.niosmess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUc0z-3CD_ni6XEjjekL7LzBfTNBCvS5I',
    appId: '1:31725064203:web:8deeaeabd2ee845c82370e',
    messagingSenderId: '31725064203',
    projectId: 'niosmess',
    authDomain: 'niosmess.firebaseapp.com',
    storageBucket: 'niosmess.firebasestorage.app',
    measurementId: 'G-31MQEJ1ELP',
  );

}