class CupertinoIconsData {
  const CupertinoIconsData._();

  static const Map<String, int> codepoints = <String, int>{
    // Chat & Communication
    'chat_bubble': 0xf254,
    'chat_bubble_fill': 0xf255,
    'chat_bubble_2': 0xf256,
    'chat_bubble_2_fill': 0xf257,
    'heart': 0xf442,
    'heart_fill': 0xf443,
    'star': 0xf4b9,
    'star_fill': 0xf4ba,
    'hand_thumbsup': 0xf437,
    'hand_thumbsup_fill': 0xf438,
    'paperplane': 0xf476,
    'paperplane_fill': 0xf477,
    'bell': 0xf3e1,
    'bell_fill': 0xf3e2,
    'flame': 0xf428,
    'flame_fill': 0xf429,
    'bolt': 0xf3ed,
    'bolt_fill': 0xf3ee,
    'sparkles': 0xf4b7,
    'mail': 0xf45e,
    'mail_fill': 0xf45f,
    'share': 0xf4ca,

    // Tech & Devices
    'device_laptop': 0xf418,
    'device_phone': 0xf41b,
    'gear_alt': 0xf430,
    'gear_alt_fill': 0xf431,
    'cpu': 0xf40f,
    'wifi': 0xf4e6,
    'shield': 0xf4a6,
    'shield_fill': 0xf4a7,
    'lock': 0xf455,
    'lock_fill': 0xf456,
    'antenna_radiowaves_left_right': 0xf3b8,
    'battery_100': 0xf3d9,
    'camera': 0xf3f5,
    'camera_fill': 0xf3f6,
    'gamecontroller': 0xf42e,
    'gamecontroller_fill': 0xf42f,
    'headphones': 0xf43e,

    // Space & Weather
    'moon': 0xf468,
    'moon_fill': 0xf469,
    'sun_max': 0xf4d3,
    'sun_max_fill': 0xf4d4,
    'cloud': 0xf402,
    'cloud_fill': 0xf403,
    'compass': 0xf40c,
    'compass_fill': 0xf40d,
    'airplane': 0xf3b0,
    'location': 0xf453,
    'location_fill': 0xf454,
    'globe': 0xf434,

    // Food & Dining
    'cup_straw': 0xf414,
    'cup_straw_fill': 0xf415,
    'cart': 0xf3fa,
    'cart_fill': 0xf3fb,
    'gift': 0xf432,
    'gift_fill': 0xf433,
    'tag': 0xf4d5,
    'tag_fill': 0xf4d6,

    // Nature & Animals
    'paw': 0xf478,
    'leaf_arrow_circlepath': 0xf44e,
    'drop': 0xf41f,
    'drop_fill': 0xf420,
    'snow': 0xf4b1,
    'wind': 0xf4e7,
    'hare': 0xf43b,
    'hare_fill': 0xf43c,
    'tortoise': 0xf4de,
    'tortoise_fill': 0xf4df,

    // Minimal & Shapes
    'circle': 0xf3ff,
    'circle_fill': 0xf401,
    'square': 0xf4b4,
    'square_fill': 0xf4b6,
    'triangle': 0xf4e0,
    'triangle_fill': 0xf4e1,
    'rhombus': 0xf4a4,
    'rhombus_fill': 0xf4a5,
    'suit_heart': 0xf4c6,
    'suit_heart_fill': 0xf4c7,
    'suit_diamond': 0xf4c4,
    'suit_diamond_fill': 0xf4c5,
    'suit_club': 0xf4c2,
    'suit_club_fill': 0xf4c3,
    'suit_spade': 0xf4c8,
    'suit_spade_fill': 0xf4c9,
  };

  static const Map<String, String> filledVariants = <String, String>{
    'chat_bubble': 'chat_bubble_fill',
    'chat_bubble_2': 'chat_bubble_2_fill',
    'heart': 'heart_fill',
    'star': 'star_fill',
    'hand_thumbsup': 'hand_thumbsup_fill',
    'paperplane': 'paperplane_fill',
    'bell': 'bell_fill',
    'flame': 'flame_fill',
    'bolt': 'bolt_fill',
    'mail': 'mail_fill',
    'device_laptop': 'device_laptop',
    'gear_alt': 'gear_alt_fill',
    'shield': 'shield_fill',
    'lock': 'lock_fill',
    'camera': 'camera_fill',
    'gamecontroller': 'gamecontroller_fill',
    'moon': 'moon_fill',
    'sun_max': 'sun_max_fill',
    'cloud': 'cloud_fill',
    'compass': 'compass_fill',
    'location': 'location_fill',
    'cup_straw': 'cup_straw_fill',
    'cart': 'cart_fill',
    'gift': 'gift_fill',
    'tag': 'tag_fill',
    'drop': 'drop_fill',
    'hare': 'hare_fill',
    'tortoise': 'tortoise_fill',
    'circle': 'circle_fill',
    'square': 'square_fill',
    'triangle': 'triangle_fill',
    'rhombus': 'rhombus_fill',
    'suit_heart': 'suit_heart_fill',
    'suit_diamond': 'suit_diamond_fill',
    'suit_club': 'suit_club_fill',
    'suit_spade': 'suit_spade_fill',
  };

  static const Map<String, List<String>> themePacks = <String, List<String>>{
    'chat': <String>[
      'chat_bubble_2',
      'heart',
      'star',
      'hand_thumbsup',
      'paperplane',
      'bell',
      'flame',
      'bolt',
      'sparkles',
      'mail',
      'share',
    ],
    'tech': <String>[
      'device_laptop',
      'device_phone',
      'gear_alt',
      'cpu',
      'wifi',
      'shield',
      'lock',
      'antenna_radiowaves_left_right',
      'battery_100',
      'gamecontroller',
      'headphones',
    ],
    'space': <String>[
      'moon',
      'sun_max',
      'cloud',
      'compass',
      'airplane',
      'location',
      'globe',
      'sparkles',
    ],
    'food': <String>[
      'cup_straw',
      'cart',
      'gift',
      'tag',
    ],
    'nature': <String>[
      'paw',
      'leaf_arrow_circlepath',
      'drop',
      'snow',
      'wind',
      'hare',
      'tortoise',
    ],
    'minimal': <String>[
      'circle',
      'square',
      'triangle',
      'rhombus',
      'suit_heart',
      'suit_diamond',
      'suit_club',
      'suit_spade',
    ],
  };

  static final List<String> allNames = codepoints.keys.toList(growable: false);
  static final List<int> allCodepoints = codepoints.values.toList(growable: false);

  static int resolveCodepoint(String name, {bool filled = false}) {
    if (filled && filledVariants.containsKey(name)) {
      final String filledName = filledVariants[name]!;
      return codepoints[filledName] ?? codepoints[name] ?? 0xf442;
    }
    return codepoints[name] ?? 0xf442;
  }
}
