const emojiCategories = {
  "Смайлы": [
    { emoji: "😀", keywords: ["улыбка", "smile", "happy", "радость"] },
    { emoji: "😃", keywords: ["улыбка", "smile", "радость"] },
    { emoji: "😄", keywords: ["улыбка", "smile", "смех"] },
    { emoji: "😁", keywords: ["улыбка", "grin", "зубы"] },
    { emoji: "😆", keywords: ["смех", "laugh", "радость"] },
    { emoji: "😅", keywords: ["смех", "пот", "sweat"] },
    { emoji: "🤣", keywords: ["смех", "laugh", "ржу"] },
    { emoji: "😂", keywords: ["смех", "слёзы", "joy"] },
    { emoji: "🙂", keywords: ["улыбка", "smile"] },
    { emoji: "🙃", keywords: ["перевернутый", "upside"] },
    { emoji: "😉", keywords: ["подмигивание", "wink"] },
    { emoji: "😊", keywords: ["улыбка", "румянец", "blush"] },
    { emoji: "😇", keywords: ["ангел", "angel", "нимб"] },
    { emoji: "🥰", keywords: ["любовь", "love", "сердечки"] },
    { emoji: "😍", keywords: ["любовь", "love", "сердца"] },
    { emoji: "🤩", keywords: ["звёзды", "star", "вау"] },
    { emoji: "😘", keywords: ["поцелуй", "kiss"] },
    { emoji: "😗", keywords: ["поцелуй", "kiss"] },
    { emoji: "😚", keywords: ["поцелуй", "kiss", "закрытые глаза"] },
    { emoji: "😙", keywords: ["поцелуй", "kiss", "улыбка"] },
    { emoji: "🥲", keywords: ["слеза", "счастливая слеза"] },
  ],

  "Жесты": [
    { emoji: "👋", keywords: ["привет", "wave", "рука", "пока"] },
    { emoji: "🤚", keywords: ["рука", "ладонь", "стоп"] },
    { emoji: "🖐", keywords: ["рука", "пять", "пальцев"] },
    { emoji: "✋", keywords: ["стоп", "stop", "рука"] },
    { emoji: "🖖", keywords: ["vulcan", "спок", "star trek"] },
    { emoji: "👌", keywords: ["ок", "ok", "хорошо", "отлично"] },
    { emoji: "🤌", keywords: ["щепотка", "итальянский", "жест"] },
    { emoji: "🤏", keywords: ["щепотка", "мало", "маленький"] },
    { emoji: "✌️", keywords: ["победа", "peace", "мир"] },
    { emoji: "🤞", keywords: ["пальцы", "удача", "скрещены"] },
    { emoji: "🤟", keywords: ["люблю", "love", "знак"] },
    { emoji: "🤘", keywords: ["рок", "rock", "рога"] },
    { emoji: "🤙", keywords: ["позвони", "call", "шака"] },
    { emoji: "👈", keywords: ["влево", "left", "указать"] },
    { emoji: "👉", keywords: ["вправо", "right", "указать"] },
    { emoji: "👆", keywords: ["вверх", "up", "указать"] },
    { emoji: "👇", keywords: ["вниз", "down", "указать"] },
    { emoji: "☝️", keywords: ["один", "вверх", "внимание"] },
    { emoji: "👍", keywords: ["лайк", "like", "класс", "хорошо"] },
    { emoji: "👎", keywords: ["дизлайк", "dislike", "плохо"] },
    { emoji: "✊", keywords: ["кулак", "fist", "сила"] },
    { emoji: "👊", keywords: ["кулак", "удар", "bump"] },
    { emoji: "🤛", keywords: ["кулак", "левый", "bump"] },
    { emoji: "🤜", keywords: ["кулак", "правый", "bump"] },
    { emoji: "👏", keywords: ["аплодисменты", "clap", "браво"] },
    { emoji: "🙌", keywords: ["руки", "ура", "celebration", "праздник"] },
    { emoji: "👐", keywords: ["руки", "открытые", "объятия"] },
    { emoji: "🤲", keywords: ["руки", "ладони", "просьба"] },
    { emoji: "🤝", keywords: ["рукопожатие", "handshake", "сделка"] },
    { emoji: "🙏", keywords: ["молитва", "pray", "спасибо", "пожалуйста"] },
  ],

  "Любовь": [
    { emoji: "❤️", keywords: ["сердце", "heart", "любовь", "красное"] },
    { emoji: "🧡", keywords: ["сердце", "оранжевый", "heart"] },
    { emoji: "💛", keywords: ["сердце", "жёлтый", "heart"] },
    { emoji: "💚", keywords: ["сердце", "зелёный", "heart"] },
    { emoji: "💙", keywords: ["сердце", "синий", "heart"] },
    { emoji: "💜", keywords: ["сердце", "фиолетовый", "heart"] },
    { emoji: "🖤", keywords: ["сердце", "чёрный", "heart"] },
    { emoji: "🤍", keywords: ["сердце", "белый", "heart"] },
    { emoji: "🤎", keywords: ["сердце", "коричневый", "heart"] },
    { emoji: "💔", keywords: ["разбитое", "сердце", "broken", "грусть"] },
    { emoji: "❣️", keywords: ["сердце", "восклицание", "любовь"] },
    { emoji: "💕", keywords: ["сердца", "два", "любовь"] },
    { emoji: "💞", keywords: ["сердца", "вращение", "любовь"] },
    { emoji: "💓", keywords: ["сердце", "бьётся", "любовь"] },
    { emoji: "💗", keywords: ["сердце", "растёт", "любовь"] },
    { emoji: "💖", keywords: ["сердце", "блеск", "любовь"] },
    { emoji: "💘", keywords: ["сердце", "стрела", "купидон"] },
    { emoji: "💝", keywords: ["сердце", "подарок", "любовь"] },
    { emoji: "💋", keywords: ["поцелуй", "губы", "kiss"] },
    { emoji: "🫶", keywords: ["сердце", "руки", "любовь"] },
    { emoji: "❤️‍🔥", keywords: ["горящее сердце", "страсть"] },
    { emoji: "❤️‍🩹", keywords: ["лечение", "восстановление"] },
  ],

  "Эмоции": [
    { emoji: "😊", keywords: ["улыбка", "счастье", "довольство"] },
    { emoji: "😌", keywords: ["спокойствие", "умиротворение"] },
    { emoji: "😏", keywords: ["ухмылка", "smirk", "самодовольство"] },
    { emoji: "😴", keywords: ["сон", "sleep", "усталость"] },
    { emoji: "😪", keywords: ["сонный", "усталость", "sleepy"] },
    { emoji: "🤤", keywords: ["слюни", "вкусно", "хочу"] },
    { emoji: "😋", keywords: ["вкусно", "yummy", "язык"] },
    { emoji: "😛", keywords: ["язык", "tongue", "дразнить"] },
    { emoji: "😜", keywords: ["подмигивание", "язык", "шутка"] },
    { emoji: "🤪", keywords: ["безумный", "crazy", "дурачиться"] },
    { emoji: "😝", keywords: ["язык", "закрытые глаза"] },
    { emoji: "🤑", keywords: ["деньги", "money", "богатство"] },
    { emoji: "🤗", keywords: ["обнимашки", "hug", "объятия"] },
    { emoji: "🤭", keywords: ["упс", "смущение", "тихий смех"] },
    { emoji: "🫢", keywords: ["ой", "удивление", "шок"] },
    { emoji: "🫣", keywords: ["подглядывание", "страх"] },
    { emoji: "🤫", keywords: ["тихо", "shh", "секрет"] },
    { emoji: "🤔", keywords: ["думает", "thinking", "размышление"] },
    { emoji: "🤐", keywords: ["молчание", "тайна", "рот на замке"] },
    { emoji: "🤨", keywords: ["скептически", "сомнение", "подозрение"] },
    { emoji: "😐", keywords: ["нейтрально", "мех", "без эмоций"] },
    { emoji: "😑", keywords: ["без выражения", "апатия"] },
    { emoji: "😶", keywords: ["без рта", "молчание"] },
    { emoji: "🫥", keywords: ["пунктир", "невидимка"] },
    { emoji: "😶‍🌫️", keywords: ["туман", "растерянность"] },
  ],

  "Грусть": [
    { emoji: "😔", keywords: ["грусть", "sad", "печаль"] },
    { emoji: "😕", keywords: ["confused", "смущение", "непонятно"] },
    { emoji: "🙁", keywords: ["грусть", "расстройство", "sad"] },
    { emoji: "☹️", keywords: ["грусть", "sad", "печаль"] },
    { emoji: "😟", keywords: ["беспокойство", "волнение"] },
    { emoji: "😞", keywords: ["разочарование", "грусть"] },
    { emoji: "😣", keywords: ["упс", "беда", "страдание"] },
    { emoji: "😖", keywords: ["боль", "страдание", "мука"] },
    { emoji: "😫", keywords: ["усталость", "tired", "измотан"] },
    { emoji: "😩", keywords: ["плач", "cry", "стресс"] },
    { emoji: "🥺", keywords: ["умоляю", "plead", "щенячий взгляд"] },
    { emoji: "😢", keywords: ["слёзы", "cry", "плач"] },
    { emoji: "😭", keywords: ["плач", "cry", "рыдание", "ревёт"] },
    { emoji: "😤", keywords: ["злость", "anger", "раздражение"] },
    { emoji: "😠", keywords: ["злость", "angry", "сердитый"] },
    { emoji: "😡", keywords: ["ярость", "rage", "fury"] },
    { emoji: "🤬", keywords: ["мат", "ругань", "злость"] },
    { emoji: "🥹", keywords: ["сдерживает слёзы", "растрогало"] },
  ],

  "Животные": [
    { emoji: "🐶", keywords: ["собака", "dog", "пёс", "щенок"] },
    { emoji: "🐱", keywords: ["кошка", "cat", "кот", "котик"] },
    { emoji: "🐭", keywords: ["мышь", "mouse", "мышка"] },
    { emoji: "🐹", keywords: ["хомяк", "hamster"] },
    { emoji: "🐰", keywords: ["кролик", "rabbit", "зайчик"] },
    { emoji: "🦊", keywords: ["лиса", "fox", "лисичка"] },
    { emoji: "🐻", keywords: ["медведь", "bear"] },
    { emoji: "🐼", keywords: ["панда", "panda"] },
    { emoji: "🐨", keywords: ["коала", "koala"] },
    { emoji: "🐯", keywords: ["тигр", "tiger"] },
    { emoji: "🦁", keywords: ["лев", "lion"] },
    { emoji: "🐮", keywords: ["корова", "cow"] },
    { emoji: "🐷", keywords: ["свинья", "pig", "хрюша"] },
    { emoji: "🐸", keywords: ["лягушка", "frog", "жаба"] },
    { emoji: "🐵", keywords: ["обезьяна", "monkey"] },
    { emoji: "🙈", keywords: ["не вижу", "обезьяна"] },
    { emoji: "🙉", keywords: ["не слышу", "обезьяна"] },
    { emoji: "🙊", keywords: ["молчу", "обезьяна"] },
    { emoji: "🐔", keywords: ["курица", "chicken", "птица"] },
    { emoji: "🐧", keywords: ["пингвин", "penguin"] },
    { emoji: "🐦", keywords: ["птица", "bird"] },
    { emoji: "🦆", keywords: ["утка", "duck"] },
    { emoji: "🦉", keywords: ["сова", "owl"] },
    { emoji: "🦋", keywords: ["бабочка", "butterfly"] },
    { emoji: "🐝", keywords: ["пчела", "bee"] },
    { emoji: "🐛", keywords: ["гусеница", "worm"] },
    { emoji: "🦄", keywords: ["единорог", "unicorn"] },
    { emoji: "🐴", keywords: ["лошадь", "horse"] },
  ],

  "Еда": [
    { emoji: "🍕", keywords: ["пицца", "pizza"] },
    { emoji: "🍔", keywords: ["бургер", "burger", "гамбургер"] },
    { emoji: "🍟", keywords: ["фри", "картошка", "картофель"] },
    { emoji: "🌭", keywords: ["хот-дог", "hotdog", "сосиска"] },
    { emoji: "🍿", keywords: ["попкорн", "popcorn", "кино"] },
    { emoji: "🧂", keywords: ["соль", "salt"] },
    { emoji: "🥓", keywords: ["бекон", "bacon"] },
    { emoji: "🥚", keywords: ["яйцо", "egg"] },
    { emoji: "🍳", keywords: ["яичница", "cooking"] },
    { emoji: "🧇", keywords: ["вафли", "waffle"] },
    { emoji: "🥞", keywords: ["блины", "pancakes"] },
    { emoji: "🧈", keywords: ["масло", "butter"] },
    { emoji: "🍞", keywords: ["хлеб", "bread"] },
    { emoji: "🥐", keywords: ["круассан", "croissant"] },
    { emoji: "🥖", keywords: ["багет", "baguette"] },
    { emoji: "🌮", keywords: ["тако", "taco"] },
    { emoji: "🌯", keywords: ["буррито", "burrito"] },
    { emoji: "🥙", keywords: ["шаурма", "kebab", "донер"] },
    { emoji: "🍝", keywords: ["паста", "спагетти", "макароны"] },
    { emoji: "🍕", keywords: ["пицца", "pizza"] },
    { emoji: "🍖", keywords: ["мясо", "meat"] },
    { emoji: "🍗", keywords: ["курица", "chicken"] },
    { emoji: "🥩", keywords: ["стейк", "steak", "мясо"] },
    { emoji: "🍰", keywords: ["торт", "cake", "пирожное"] },
    { emoji: "🎂", keywords: ["торт", "день рождения", "birthday"] },
    { emoji: "🧁", keywords: ["кекс", "cupcake"] },
    { emoji: "🍪", keywords: ["печенье", "cookie"] },
    { emoji: "🍩", keywords: ["пончик", "donut"] },
    { emoji: "🍫", keywords: ["шоколад", "chocolate"] },
    { emoji: "🍬", keywords: ["конфета", "candy"] },
    { emoji: "🍭", keywords: ["леденец", "lollipop"] },
  ],

  "Напитки": [
    { emoji: "☕", keywords: ["кофе", "coffee", "чай"] },
    { emoji: "🍵", keywords: ["чай", "tea"] },
    { emoji: "🧃", keywords: ["сок", "juice", "коробка"] },
    { emoji: "🧋", keywords: ["bubble tea", "бабл ти"] },
    { emoji: "🥤", keywords: ["напиток", "drink", "стакан"] },
    { emoji: "🧊", keywords: ["лёд", "ice"] },
    { emoji: "🍶", keywords: ["саке", "sake"] },
    { emoji: "🍺", keywords: ["пиво", "beer"] },
    { emoji: "🍻", keywords: ["пиво", "cheers", "за здоровье"] },
    { emoji: "🍷", keywords: ["вино", "wine"] },
    { emoji: "🥂", keywords: ["шампанское", "champagne", "тост"] },
    { emoji: "🍸", keywords: ["коктейль", "cocktail"] },
    { emoji: "🍹", keywords: ["тропический", "коктейль"] },
    { emoji: "🍾", keywords: ["шампанское", "праздник"] },
    { emoji: "🥃", keywords: ["виски", "whiskey"] },
  ],

  "Активность": [
    { emoji: "⚽", keywords: ["футбол", "soccer", "мяч"] },
    { emoji: "🏀", keywords: ["баскетбол", "basketball"] },
    { emoji: "🏈", keywords: ["регби", "football", "американский футбол"] },
    { emoji: "⚾", keywords: ["бейсбол", "baseball"] },
    { emoji: "🥎", keywords: ["софтбол", "softball"] },
    { emoji: "🎾", keywords: ["теннис", "tennis"] },
    { emoji: "🏐", keywords: ["волейбол", "volleyball"] },
    { emoji: "🏉", keywords: ["регби", "rugby"] },
    { emoji: "🥏", keywords: ["фрисби", "frisbee"] },
    { emoji: "🎱", keywords: ["бильярд", "billiards", "пул"] },
    { emoji: "🏓", keywords: ["пинг-понг", "ping pong", "настольный теннис"] },
    { emoji: "🏸", keywords: ["бадминтон", "badminton"] },
    { emoji: "🥅", keywords: ["ворота", "goal"] },
    { emoji: "🏒", keywords: ["хоккей", "hockey"] },
    { emoji: "🏑", keywords: ["хоккей на траве"] },
    { emoji: "🥍", keywords: ["лакросс", "lacrosse"] },
    { emoji: "🏏", keywords: ["крикет", "cricket"] },
    { emoji: "🎮", keywords: ["игра", "game", "геймпад", "gaming"] },
    { emoji: "🕹️", keywords: ["джойстик", "joystick", "arcade"] },
    { emoji: "🎯", keywords: ["дартс", "target", "цель"] },
    { emoji: "🎲", keywords: ["кости", "dice", "игра"] },
    { emoji: "♠️", keywords: ["пики", "карты"] },
    { emoji: "♥️", keywords: ["черви", "карты"] },
    { emoji: "♦️", keywords: ["бубны", "карты"] },
    { emoji: "♣️", keywords: ["трефы", "карты"] },
    { emoji: "🎴", keywords: ["карты", "игра"] },
    { emoji: "🀄", keywords: ["маджонг", "игра"] },
    { emoji: "🎭", keywords: ["театр", "маски"] },
    { emoji: "🎨", keywords: ["искусство", "art", "палитра"] },
  ],

  "Путешествия": [
    { emoji: "🚗", keywords: ["машина", "car", "авто"] },
    { emoji: "🚕", keywords: ["такси", "taxi"] },
    { emoji: "🚙", keywords: ["внедорожник", "suv"] },
    { emoji: "🚌", keywords: ["автобус", "bus"] },
    { emoji: "🚎", keywords: ["троллейбус"] },
    { emoji: "🏎️", keywords: ["гоночная", "race car"] },
    { emoji: "🚓", keywords: ["полиция", "police"] },
    { emoji: "🚑", keywords: ["скорая", "ambulance"] },
    { emoji: "🚒", keywords: ["пожарная", "fire truck"] },
    { emoji: "🚐", keywords: ["минивэн", "minibus"] },
    { emoji: "🚚", keywords: ["грузовик", "truck"] },
    { emoji: "🚛", keywords: ["фура", "truck"] },
    { emoji: "🚜", keywords: ["трактор", "tractor"] },
    { emoji: "🏍️", keywords: ["мотоцикл", "motorcycle"] },
    { emoji: "🛵", keywords: ["скутер", "scooter"] },
    { emoji: "🚲", keywords: ["велосипед", "bike"] },
    { emoji: "✈️", keywords: ["самолёт", "airplane", "полёт"] },
    { emoji: "🚁", keywords: ["вертолёт", "helicopter"] },
    { emoji: "🚂", keywords: ["поезд", "train"] },
    { emoji: "🚆", keywords: ["поезд", "train"] },
    { emoji: "🚇", keywords: ["метро", "subway"] },
    { emoji: "🚊", keywords: ["трамвай", "tram"] },
    { emoji: "🚝", keywords: ["монорельс", "monorail"] },
    { emoji: "🚄", keywords: ["скоростной поезд", "bullet train"] },
    { emoji: "🚅", keywords: ["скоростной поезд"] },
    { emoji: "🚈", keywords: ["электричка"] },
    { emoji: "🚞", keywords: ["горная дорога"] },
    { emoji: "🚃", keywords: ["вагон", "railway car"] },
  ],

  "Объекты": [
    { emoji: "💻", keywords: ["компьютер", "laptop", "ноутбук"] },
    { emoji: "🖥️", keywords: ["компьютер", "пк", "монитор", "desktop"] },
    { emoji: "⌨️", keywords: ["клавиатура", "keyboard"] },
    { emoji: "🖱️", keywords: ["мышь", "mouse"] },
    { emoji: "🖨️", keywords: ["принтер", "printer"] },
    { emoji: "📱", keywords: ["телефон", "phone", "смартфон", "мобильный"] },
    { emoji: "☎️", keywords: ["телефон", "старый", "ретро"] },
    { emoji: "📞", keywords: ["телефон", "трубка"] },
    { emoji: "📟", keywords: ["пейджер", "pager"] },
    { emoji: "📠", keywords: ["факс", "fax"] },
    { emoji: "📺", keywords: ["телевизор", "tv", "тв"] },
    { emoji: "📻", keywords: ["радио", "radio"] },
    { emoji: "🎙️", keywords: ["микрофон", "mic", "podcast"] },
    { emoji: "🎚️", keywords: ["регулятор", "slider", "микшер"] },
    { emoji: "🎛️", keywords: ["пульт", "control", "регулятор"] },
    { emoji: "🧭", keywords: ["компас", "compass", "навигация"] },
    { emoji: "⏰", keywords: ["будильник", "alarm", "часы"] },
    { emoji: "⏱️", keywords: ["секундомер", "timer", "stopwatch"] },
    { emoji: "⏲️", keywords: ["таймер", "timer"] },
    { emoji: "🕰️", keywords: ["часы", "clock", "старинные"] },
    { emoji: "⌛", keywords: ["песочные часы", "hourglass"] },
    { emoji: "⏳", keywords: ["песочные часы", "время"] },
    { emoji: "📡", keywords: ["антенна", "satellite"] },
    { emoji: "🔋", keywords: ["батарейка", "battery"] },
    { emoji: "🔌", keywords: ["розетка", "plug"] },
    { emoji: "💡", keywords: ["лампочка", "idea", "идея"] },
    { emoji: "🔦", keywords: ["фонарик", "flashlight"] },
    { emoji: "🕯️", keywords: ["свеча", "candle"] },
  ],

  "Символы": [
    { emoji: "🔥", keywords: ["огонь", "fire", "горит", "топ"] },
    { emoji: "✨", keywords: ["блеск", "sparkles", "сверкает"] },
    { emoji: "💫", keywords: ["звёзды", "dizzy", "кружится"] },
    { emoji: "⭐", keywords: ["звезда", "star"] },
    { emoji: "🌟", keywords: ["звезда", "блеск", "сияние"] },
    { emoji: "✅", keywords: ["галочка", "check", "да", "готово"] },
    { emoji: "❌", keywords: ["крест", "нет", "x", "отмена"] },
    { emoji: "❗", keywords: ["восклицание", "важно", "внимание"] },
    { emoji: "❓", keywords: ["вопрос", "question"] },
    { emoji: "❔", keywords: ["вопрос", "белый"] },
    { emoji: "❕", keywords: ["восклицание", "белое"] },
    { emoji: "💯", keywords: ["сто", "100", "топ", "отлично"] },
    { emoji: "🎉", keywords: ["праздник", "party", "конфетти"] },
    { emoji: "🎊", keywords: ["конфетти", "celebration", "праздник"] },
    { emoji: "🎁", keywords: ["подарок", "gift", "present"] },
    { emoji: "🎈", keywords: ["шарик", "balloon", "воздушный"] },
    { emoji: "🎀", keywords: ["бант", "ribbon"] },
    { emoji: "🏆", keywords: ["кубок", "trophy", "победа", "first"] },
    { emoji: "🥇", keywords: ["золото", "первое", "место", "gold"] },
    { emoji: "🥈", keywords: ["серебро", "второе", "место", "silver"] },
    { emoji: "🥉", keywords: ["бронза", "третье", "место", "bronze"] },
    { emoji: "⚡", keywords: ["молния", "lightning", "быстро"] },
    { emoji: "💥", keywords: ["взрыв", "boom", "бум"] },
    { emoji: "💢", keywords: ["злость", "anger"] },
    { emoji: "💨", keywords: ["ветер", "быстро", "дым"] },
    { emoji: "💦", keywords: ["капли", "вода", "пот"] },
    { emoji: "💤", keywords: ["сон", "sleep", "zzz"] },
    { emoji: "🕳️", keywords: ["дыра", "hole"] },
    { emoji: "🔔", keywords: ["колокольчик", "bell", "звонок"] },
    { emoji: "🔕", keywords: ["без звука", "mute"] },
    { emoji: "🎵", keywords: ["нота", "music", "музыка"] },
    { emoji: "🎶", keywords: ["ноты", "music", "песня"] },
  ],
};
